---
kind: pipeline
trigger:
  event:
    - push
    - cron
  branch:
    - master

steps:
  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      semantic_release: false
      update_readme_toc: true
      git_method: gh
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_token
      update_docker_readme: true
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
      docker_repo: cenk1cenk2/lerna-dev
      readme_location: README.md
    when:
      event:
        - push
        - cron
      branch:
        - master

  - name: publish-12
    image: plugins/docker
    working_dir: /drone/src/build
    settings:
      repo: cenk1cenk2/lerna-dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - 12
      build_args:
        - NODE_VERSION=12
    depends_on:
      - semantic-release
    when:
      event:
        - push
        - cron
      branch:
        - master

  - name: publish-14
    image: plugins/docker
    working_dir: /drone/src/build
    settings:
      repo: cenk1cenk2/lerna-dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - 14
      build_args:
        - NODE_VERSION=14
    depends_on:
      - semantic-release
    when:
      event:
        - push
        - cron
      branch:
        - master
